# Generated by Django 3.0.5 on 2020-04-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0002_auto_20200404_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='publication_date',
            field=models.DateField(),
        ),
    ]
